# Generated by Django 4.0 on 2021-12-20 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_profile_course_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='course',
        ),
    ]
