# Generated by Django 4.0 on 2021-12-19 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_task_bonus_coin'),
        ('customer', '0002_profile_course_profile_user'),
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spent_coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.coinbase')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.course')),
                ('from_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Earn_coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.coinbase')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.task')),
                ('to_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.profile')),
            ],
        ),
    ]
