# Generated by Django 4.0 on 2021-12-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_task_bonus_coin'),
        ('customer', '0002_profile_course_profile_user'),
        ('bank', '0002_spent_coin_earn_coin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Earn_coin',
            new_name='EarnCoin',
        ),
        migrations.RenameModel(
            old_name='Spent_coin',
            new_name='SpentCoin',
        ),
    ]
