# Generated by Django 4.0 on 2021-12-19 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_rename_earn_coin_earncoin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earncoin',
            name='bank',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='bank.coinbase'),
        ),
        migrations.AlterField(
            model_name='spentcoin',
            name='bank',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='bank.coinbase'),
        ),
    ]
