# Generated by Django 4.0 on 2021-12-19 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_alter_earncoin_bank_alter_spentcoin_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spentcoin',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bank.coinbase'),
        ),
    ]
