# Generated by Django 4.0 on 2021-12-15 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_profile_course'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customer.user'),
            preserve_default=False,
        ),
    ]
