# Generated by Django 4.0 on 2021-12-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_profile_course_profile_user'),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='video',
        ),
        migrations.RemoveField(
            model_name='video',
            name='banned',
        ),
        migrations.RemoveField(
            model_name='video',
            name='course_id',
        ),
        migrations.AlterField(
            model_name='homework',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='api.task'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='customer.user'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('banned', models.BooleanField(default=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='api.course')),
            ],
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='homework_lesson', to='api.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task_lesson', to='api.lesson'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='video_lesson', to='api.lesson'),
            preserve_default=False,
        ),
    ]
