# Generated by Django 4.0 on 2021-12-17 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_task_video_remove_video_banned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='task',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='task',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='video',
            name='lesson',
        ),
        migrations.AddField(
            model_name='course',
            name='lesson',
            field=models.ManyToManyField(to='api.Lesson'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='task',
            field=models.ManyToManyField(to='api.Task'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.ManyToManyField(to='api.Video'),
        ),
        migrations.AddField(
            model_name='task',
            name='homework',
            field=models.ManyToManyField(to='api.Homework'),
        ),
    ]
