# Generated by Django 4.0 on 2021-12-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_homework_lesson_remove_homework_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lesson',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='task',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video',
        ),
        migrations.RemoveField(
            model_name='task',
            name='homework',
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework_lesson', to='api.lesson'),
        ),
        migrations.AddField(
            model_name='homework',
            name='task',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='task', to='api.task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='api.course'),
        ),
        migrations.AddField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_lesson', to='api.lesson'),
        ),
        migrations.AddField(
            model_name='video',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_lesson', to='api.lesson'),
        ),
    ]
