# Generated by Django 4.0 on 2021-12-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_course_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
    ]
