# Generated by Django 4.0 on 2021-12-17 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_course_lesson_remove_lesson_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='lesson',
        ),
    ]
