# Generated by Django 4.0 on 2021-12-17 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_profile_course_profile_user'),
        ('api', '0005_remove_homework_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='create_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.FileField(null=True, upload_to='homework'),
        ),
        migrations.AddField(
            model_name='task',
            name='github_link',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='customer.user'),
        ),
        migrations.DeleteModel(
            name='Homework',
        ),
    ]
