# Generated by Django 4.0 on 2021-12-18 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_profile_course_profile_user'),
        ('api', '0006_task_create_at_task_file_task_github_link_task_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='file',
        ),
        migrations.RemoveField(
            model_name='task',
            name='github_link',
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='homework')),
                ('github_link', models.URLField(null=True)),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='api.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_user', to='customer.user')),
            ],
        ),
    ]
