# Generated by Django 4.0 on 2021-12-19 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_profile_course_profile_user'),
        ('api', '0008_homework_feedback_homework_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.user'),
        ),
    ]
