# Generated by Django 4.0 on 2021-12-19 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_homework_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='correct',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
