# Generated by Django 4.0 on 2021-12-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_lesson_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bonus_coin',
            field=models.IntegerField(null=True),
        ),
    ]
