# Generated by Django 4.0 on 2021-12-20 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_remove_profile_course'),
        ('api', '0013_task_bonus_coin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='banned',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='banned',
        ),
        migrations.AddField(
            model_name='course',
            name='profile',
            field=models.ManyToManyField(blank=True, to='customer.Profile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='profile',
            field=models.ManyToManyField(blank=True, to='customer.Profile'),
        ),
    ]
